% -------------------------------------------------------------------
%  Generated by MATLAB on 19-May-2022 17:51:41
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('HA_1Matlabfile.mat');

A = ...
  [4 0 0;
   0 -9 0;
   0 0 -1];


B = ...
  [1 0;
   1 0;
   0 1];

B1 = [1; 1; 0];

B2 = [0; 0; 1];

C = ...
  [-8 -9 1;
   0 3 -3];

C1 = [-8 -9 1];

C2 = [0 3 -3];

Co = ...
  [1 0 4 0 16 0;
   1 0 -9 0 81 0;
   0 1 0 -1 0 1];

F1 = [17.307692307692307 -0.30769230769230771 0];

F2 = [0 0 10];

T4 = saveVarsMat.T4; % <1x1 sym> unsupported class

ans = saveVarsMat.ans; % <1x1 sym> unsupported class

f1 = saveVarsMat.f1; % <1x1 sym> unsupported class

f2 = saveVarsMat.f2; % <1x1 sym> unsupported class

f3 = saveVarsMat.f3; % <1x1 sym> unsupported class

lamda = saveVarsMat.lamda; % <1x1 sym> unsupported class

x1 = saveVarsMat.x1; % <1x1 sym> unsupported class

x2 = saveVarsMat.x2; % <1x1 sym> unsupported class

x3 = saveVarsMat.x3; % <1x1 sym> unsupported class

clear saveVarsMat;
